language: node_js

node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.11"

before_install:
  - npm conf set strict-ssl false

script:
  - npm run-script test

notifications:
  email:
    - tomaz+travisci@tomaz.me
